version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - aws eks --region us-east-1 update-kubeconfig --name test
  build:
    commands:
      - kubectl apply -f service.yaml
